name: UniGarmentManip
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.7.22
  - click=8.0.4
  - contourpy=1.0.5
  - cudatoolkit=11.0.221
  - cycler=0.11.0
  - dbus=1.13.18
  - embree=2.17.7
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.63.1
  - glob2=0.7
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - ilmbase=2.5.5
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - joblib=1.2.0
  - jpeg=9b
  - kiwisolver=1.4.4
  - lcms2=2.12
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libedit=3.1.20221030
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openexr=2.5.5
  - openexr-python=1.3.2
  - openssl=1.1.1o
  - packaging=23.1
  - pcre=8.45
  - pillow=9.3.0
  - pip=23.3
  - plotly=5.9.0
  - pyembree=0.1.6
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - python=3.8.0
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.7.1
  - qt=5.9.7
  - readline=7.0
  - setuptools=68.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.33.0
  - tenacity=8.2.2
  - tk=8.6.12
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.3.3
  - typing_extensions=4.7.1
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - absl-py==2.0.0
    - addict==2.4.0
    - ansi2html==1.8.0
    - asttokens==2.4.0
    - attrs==23.1.0
    - backcall==0.2.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.3.0
    - cloudpickle==1.2.2
    - comm==0.1.4
    - configargparse==1.7
    - dash==2.14.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==4.4.2
    - drjit==0.4.3
    - executing==2.0.0
    - fastjsonschema==2.18.1
    - flask==2.2.5
    - future==0.18.3
    - google-auth==2.23.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.59.0
    - gtimer==1.0.0b5
    - gym==0.14.0
    - h5py==3.10.0
    - hydra-core==0.11.3
    - idna==3.4
    - imageio==2.31.5
    - imageio-ffmpeg==0.4.9
    - importlib-metadata==6.8.0
    - info-nce-pytorch==0.1.4
    - ipython==8.12.3
    - ipywidgets==8.1.1
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.2
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-core==5.4.0
    - jupyterlab-widgets==3.0.9
    - llvmlite==0.39.1
    - lmdb==1.4.1
    - markdown==3.5
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - mitsuba==3.4.0
    - moviepy==1.0.3
    - msgpack==1.0.7
    - msgpack-numpy==0.4.8
    - nbformat==5.7.0
    - nest-asyncio==1.5.8
    - numba==0.56.4
    - numpy==1.20.3
    - oauthlib==3.2.2
    - omegaconf==1.4.1
    - open3d==0.17.0
    - opencv-python==4.8.1.78
    - pandas==2.0.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.11.0
    - pointnet2==3.0.0
    - pointnet2-ops==3.0.0
    - prefetch-generator==1.0.3
    - proglog==0.1.10
    - prompt-toolkit==3.0.39
    - protobuf==4.24.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyglet==1.3.2
    - pygments==2.16.1
    - pyquaternion==0.9.9
    - pytorch-lightning==0.7.1
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rpds-py==0.10.6
    - rsa==4.9
    - scikit-learn==1.3.1
    - scipy==1.10.1
    - shapley==1.0.3
    - sk-video==1.1.10
    - stack-data==0.6.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.2.0
    - tqdm==4.66.1
    - traitlets==5.11.2
    - trimesh==4.0.1
    - tzdata==2023.3
    - urllib3==2.0.7
    - wcwidth==0.2.8
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.9
    - zipp==3.17.0

